baseURL = 'https://Kile578.github.io'
languageCode = 'en-us'
title = 'My Cybersecurity Blog'
theme = 'ananke'
summaryLength = 50

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "TryHackMe"
    url = "/tryhackme/"
    parent = "Projects"
    weight = 31
  [[menu.main]]
    name = "Home Lab"
    url = "/homelab/"
    parent = "Projects"
    weight = 32
  [[menu.main]]
    name = "Security Tools"
    url = "/tools/"
    parent = "Projects"
    weight = 33
  [[menu.main]]
    name = "CTF Writeups"
    url = "/ctf/"
    parent = "Projects"
    weight = 34
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4