baseURL = 'https://Kile578.github.io'
languageCode = 'en-us'
title = 'My Cybersecurity Blog'
theme = 'ananke'
summaryLength = 50

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "TryHackMe"
    url = "/projects/tryhackme/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5